config/routes.rb
# ATTENTION: when adding new paths like /signin or /unearth_treasure, make
# sure to add the path name to friendlyID's reserved words under
# config/initializers/friendly_id.rb
Rails.application.routes.draw do
  root to: 'treasures#index'

  get '/tags/autocomplete', to: 'tags#autocomplete', defaults: { format: 'json' }
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/unearth_treasure' => 'treasures#unearth_treasure', as: :unearth_treasure


  get '/github/tree', to: 'octokit#tree'
  get '/github/repos', to: 'octokit#repos'
  get '/github/branches', to: 'octokit#branches'
  get '/github/content', to: 'octokit#content'

  resources :comments, only: %w(new create show), defaults: { format: 'js' }

  resources :users, only: [] do
    resources :treasures, only: [:index]
  end

  resources :treasures, only: %w(new create index show edit update), path: "" do
    resources :votes, only: %w(create)#, defaults: { format: 'js' }
  end
end

app/models/treasure.rb
class Treasure < ActiveRecord::Base
  # Attrs
  attr_accessor :unearthing

  # Slug
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Tagging
  acts_as_taggable

  # Associations
  has_many :snippets, as: :snippetable, counter_cache: true
  has_many :comments, inverse_of: :treasure, counter_cache: true
  belongs_to :user, inverse_of: :treasures
  has_many :votes
  has_many :voting_users, through: :votes, source: :user

  accepts_nested_attributes_for :snippets, :reject_if => :all_blank, :allow_destroy => true

  # Validations
  validates :title, presence: true, uniqueness: true
  validates :user, presence: true, if: :unearthing

  # Search
  update_index 'treasures#treasure', :self

  # Methods

  def snippets_attributes
    binding.pry
  end

  def tags_string
    tag_list.join(', ')
  end
end

app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
  after_action :set_cookie, only: [:index]
  before_filter :authenticate_user!, only: [:unearth_treasure]
  respond_to :html

  def show
    @treasure = Treasure.friendly.find params[:id]
  end

  def new
    @treasure = Treasure.new
    @treasure.snippets.build
  end

  def edit
    @treasure = current_user.treasures.where(slug: params[:id]).first
    render :edit
  end

  def update
    @treasure = current_user.treasures.where(slug: params[:id]).first
    if @treasure.update(params.for(@treasure).refine)
      redirect_to @treasure
    else
      render :edit
    end
  end

  # step 1 of creation: validate treasure and then bury it in session
  def create
    refined_params = params.for(Treasure).refine
    @treasure = Treasure.new refined_params
    if @treasure.valid?
      session[:hidden_treasure] = refined_params.to_json
      redirect_to :unearth_treasure
    else
      render :new
    end
  end

  # step 2 of creation: ensure worthiness by authentication, dig in session, claim and save treasure
  def unearth_treasure
    @treasure = Treasure.new JSON.parse session[:hidden_treasure]
    @treasure.user = current_user
    @treasure.unearthing = true
    session[:hidden_treasure] = nil
    if @treasure.save
      redirect_to @treasure
    else
      render :new
    end
  end

  def index
    @search = TreasureSearch.new(search_params)
    @treasures = @search.search.page(params[:page])
  end

  private

    def set_cookie
      cookies[:visited_treasures_io] = true
    end

    def search_params
      result = params[:treasure_search] || {}
      result.merge!({user_id: params[:user_id].to_i}) if params[:user_id]
      result
     end
end

app/views/treasures/_form.html.slim
= simple_form_for treasure do |f|
  .row
    .col-md-8
      = f.input :title, placeholder: 'Please enter a title...', label: false
      = f.input :description, as: :text, placeholder: '...and a description.', label: false, id: "treasure_description", input_html: { class: "collapse" }
    .col-md-4
      button.btn.btn-default.pull-right[type="button" data-toggle="collapse" data-target="#treasure_description"] Add Description
      ul#tags.form-group
      = f.hidden_field :tag_list, value: @treasure.tags_string
    = f.simple_fields_for :snippets do |snippet|
      = render '/treasures/snippet_fields', :f => snippet
      .links
        = link_to_add_association f, :snippets, title: "Add another code snippet"  do
          i.fa.fa-plus.fa-2x
        = f.button :submit, value: 'Save', class: "pull-right"

app/views/treasures/_search.html.slim
= simple_form_for @search || TreasureSearch.new, url: treasures_path, method: :get do |f|
  = f.input :tag_list, as: :hidden
  = f.input :query, wrapper: :group, label:false do
    = f.input_field :query, class: 'form-control', placeholder: 'search'
    .input-group-btn
      button.btn.btn-default[type="submit"]
        i.fa.fa-search

app/views/treasures/_snippet.html.slim
.row.snippet
  .col-md-9
    pre
      code
        == snippet.code
  .col-md-3
    .well
      = snippet.description

app/views/treasures/_snippet_fields.html.slim
.nested-fields
  .row
    .col-md-12
      = link_to_remove_association f, class: 'pull-right', title: "Remove this code snippet" do
        i.fa.fa-times.fa-2x
      ul.nav.nav-tabs[role="tablist"]
        li[class="#{'active' if f.object.github?}"]
          a[href="#github" role="tab" data-toggle="tab"] Import Github code
        li[class="#{'active' if !f.object.github?}"]
          a[href="#code" role="tab" data-toggle="tab"] Code input
  .row.nav-content
    .col-md-12
      .well.nav-panes
        .row
          .col-md-12
            .tab-content
              .tab-pane#github[class="#{'active' if f.object.github?}"]
                = f.input :github_path, input_html: { class: "codepicker" }, label: "Find files on Github", placeholder: "my_user/my_repo/my_branch/Readme.txt"
              .tab-pane#code[class="#{'active' if !f.object.github?}"]
          .col-md-9
              = f.input :code, input_html: { class: "codeedit", rows: 15}
          .col-md-3
            = f.input :description, input_html: {rows: 21}

app/views/treasures/_tags.html.slim
.tag-list
  - @search.available_tags.each do |tag|
    a.btn.btn-default.btn-sm> class="#{@search.tags && @search.tags.include?(tag['term']) ? 'active' : ''}" href="#{original_path(tag, @search, params)}"
      = tag["term"]
      span.badge=< tag["count"]

app/views/treasures/_treasure_short.html.slim
= link_to treasure_path(treasure.slug || treasure.id), class: 'treasure_link_no_hover' do
  .well.well-sm
    div.pull-right.icons
      i.fa.fa-code>
      => treasure.snippets_count
      | &emsp;
      i.fa.fa-star-o>
      => treasure.votes_count
    h4= treasure.title
    p= treasure.description
    ul.tag-list
      - treasure.tags.each do |tag|
        li.btn.btn-default.btn-xs= tag

app/views/treasures/edit.html.slim
h3
  | Edit
  =<> @treasure.title


= render 'form', treasure: @treasure

app/views/treasures/index.html.slim
- unless false #cookies[:visited_treasures_io]
  -content_for :below_header do
    .row.map-background
      .path-left-background.hidden-xs
      .path-right-background.visible-md.visible-lg
      .col-md-6.col-md-offset-1.main-call-to-action
        .col-sm-6.hidden-xs
          h2 Find Treasures
          p.cta-explanation
            | You want to
            strong< find existing
            br
            strong> code treasures
            | to help
            br
            | with your current project?
        .col-xs-12.col-sm-6
          h2 Share Treasures
          p.cta-explanation
            | You've got a
            strong<> piece of code
            br
            | lying around that could
            br
            strong> become a lib
            | of it's own?
            br
            br
            = link_to "Create a Treasure", "#{ENV['HTTPS_URL']}/new", class: "btn btn-large btn-primary visible-xs-inline-block visible-sm-inline-block"
      .col-md-4.visible-md.visible-lg
        = link_to "Create a Treasure", new_treasure_path, class: "btn btn-large btn-primary main-cta-button"
        / = simple_form_for Treasure.new do |f|
        /   = f.input :description, label: 'Give us a Github link to a file or just paste in code:'
        /   = f.button :submit, value: 'Continue'
.search-container
  .col-md-9
    = render "search"
  .col-md-3
    = render "tags"
.row
  .col-md-9
    - if @treasures.any?
      - @treasures.each do |treasure|
        = render 'treasure_short', treasure: treasure
    - else
      .well
        | No Treasures found for your search.

app/views/treasures/new.html.slim
h3 Create a new treasure

= simple_form_for @treasure do |f|
  .row
    .col-md-6
      = f.input :title, placeholder: 'Please enter a title...', label: false
      = f.input :description, as: :text, placeholder: '...and a description.', label: false, id: "treasure_description", input_html: { class: "collapse" }
    .col-md-6
      button.btn.btn-default.pull-right[type="button" data-toggle="collapse" data-target="#treasure_description"] Add Description
      ul#tags.form-group
      = f.hidden_field :tag_list, value: @treasure.tags_string
    = f.simple_fields_for :snippets do |snippet|
      = render 'snippet_fields', :f => snippet
      .links
        = link_to_add_association f, :snippets, title: "Add another code snippet"  do
          i.fa.fa-plus.fa-2x
        = f.button :submit, value: 'Save', class: "pull-right"

app/views/treasures/show.html.slim
.row
  .col-md-12
    - if current_user && !current_user.voted_treasures.include?(@treasure)
      = link_to treasure_votes_path(treasure_id: @treasure.id), method: :POST, remote: true, class: "pull-right", title: "Favorite this Treasure", id: 'new_vote' do
        i.fa.fa-star-o.fa-2x.star-icon
    - else
      i.fa.fa-star.fa-2x.star-icon.pull-right
    h3
      - if @treasure.user == current_user
        => link_to edit_treasure_path(params[:id]) do
          i.fa.fa-pencil
      = @treasure.title
    .tag-list
      - @treasure.tags.each do |tag|
        a.btn.btn-default.btn-sm= tag


- @treasure.snippets.each do |snippet|
  = render "snippet", snippet: snippet

.row
  .col-md-12
    h4 Comments
    ul#comments
      - @treasure.comments.each do |comment|
        li= render 'comments/show', comment: comment
.row
  .col-md-12
    h4 Add a Comment
    = render 'comments/new', treasure: @treasure, comment: Comment.new