config/routes.rb
# ATTENTION: when adding new paths like /signin or /unearth_treasure, make
# sure to add the path name to friendlyID's reserved words under
# config/initializers/friendly_id.rb
Rails.application.routes.draw do
  root to: 'treasures#index'

  get '/tags/autocomplete', to: 'tags#autocomplete', defaults: { format: 'json' }
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/unearth_treasure' => 'treasures#unearth_treasure', as: :unearth_treasure


  get '/github/tree', to: 'octokit#tree'
  get '/github/repos', to: 'octokit#repos'
  get '/github/branches', to: 'octokit#branches'
  get '/github/content', to: 'octokit#content'

  resources :comments, only: %w(new create show), defaults: { format: 'js' }

  resources :users, only: [] do
    resources :treasures, only: [:index]
  end

  resources :treasures, only: %w(new create index show edit update), path: "" do
    resources :votes, only: %w(create)#, defaults: { format: 'js' }
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag "logo-transparent.png", alt: "treasures.io"
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        li= link_to 'Create Treasure', "#{ENV['HTTPS_URL']}/new"
        - if user_signed_in?
          li= link_to "My Treasures", user_treasures_path(current_user)

      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li= link_to signout_path do
            i.fa.fa-sign-out
            span Sign out
        - else
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              | Sign in
              span.caret
            ul.dropdown-menu[role="menu"]
              li= link_to "#{ENV['HTTPS_URL']}/auth/github" do
                i.fa.fa-github>
                span with Github
              li= link_to "#{ENV['HTTPS_URL']}/auth/heroku" do
                i.fa.icon-heroku>
                span with Heroku
              - unless Rails.env.production?
                li= link_to "/auth/developer" do
                  i.fa.fa-repeat>
                  span as dev

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Treasures.io'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'R14 Team373'}"
    = stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag "favicon.png" , rel: "shortcut icon"
  body
    header
      = render 'layouts/navigation'
    = render 'layouts/messages'
    = content_for :below_header
    main[role="main"]
      .container
        == yield

app/views/layouts/comment_add.js.erb
$("#comments").append("<li><%= escape_javascript(yield) %></li>");
$('#new_comment').find("input[type=text], textarea").val("");
$('#new_comment').find(".nested-fields").remove();

app/views/layouts/comment_replace.js.erb
$("#new_comment").replaceWith("<%= escape_javascript(yield) %>");

app/views/layouts/vote_replace.js.erb
$("#new_vote").replaceWith("<%= escape_javascript(yield) %>");